### ISSUE TITLE
Thanks for your aricle  in PHP architect

### ISSUE THREAD

**Issue by jaapjansma** [lalwanivikas/php-mysql-chart-demo#1]
Hye Vikas,

Thanks for you article about Fusioncharts. I was going to get started then I discovered that fusioncharts is commercial licensed piece of library software. My assumption was that it was open source and freely to reuse. Am I mistaken and is fusioncharts open source and ifso where do i find the source?
Thanks,
Jaap Jansma

**Comment by lalwanivikas** [comment]
Jaap, FusionCharts is free to use in personal or non-commercial projects only.

If you want to use it in a commercial application, you will have to [buy a license](http://www.fusioncharts.com/buy/).

**Comment by jaapjansma** [comment]
@lalwanivikas thanks for the update.
